#!/usr/bin/env bash
#
# Generate the local development .env (idempotent). Never overwrites an existing
# file, so developer-supplied secrets are preserved. The values here wire the app
# to the local Postgres cluster provisioned by .cursor/db.sh. Real integration
# secrets (Stripe, AI Gateway, USPTO, ...) stay unset by design — the S00 shell
# boots unconfigured and reports an honest integration inventory.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
env_file="$repo_root/.env"

# Next.js loads .env from its own project directory (apps/web), while the rest of
# the toolchain (migrations, vitest, check:env) reads the workspace-root .env.
# A symlink keeps a single source of truth so `next dev` sees the same values.
link_web_env() {
  local link="$repo_root/apps/web/.env"
  if [[ -d "$repo_root/apps/web" && ! -e "$link" ]]; then
    ln -sf ../../.env "$link"
    echo "[env] Linked apps/web/.env -> ../../.env (for Next.js)"
  fi
}

if [[ -f "$env_file" ]]; then
  echo "[env] .env already present — leaving it untouched."
  link_web_env
  exit 0
fi

app_role="${PATENT_APP_ROLE:-patent_app_rls}"
owner_role="$(id -un)"
db_name="${PATENT_DB_NAME:-patent}"
pgport="${PGPORT:-5432}"
secret="$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")"

cat >"$env_file" <<EOF
# Local development environment — generated by .cursor/write-dotenv.sh.
# Gitignored. Never commit real secrets.
NODE_ENV=development

# Local Postgres (two-role RLS model provisioned by .cursor/db.sh)
DATABASE_URL=postgresql://$app_role@127.0.0.1:$pgport/$db_name
DATABASE_MIGRATION_URL=postgresql://$owner_role@127.0.0.1:$pgport/$db_name

# Better Auth (S01)
BETTER_AUTH_SECRET=$secret
BETTER_AUTH_URL=http://localhost:3000
EOF

echo "[env] Wrote $env_file"
link_web_env
